# 19-catalogo-service.yml
apiVersion: v1
kind: Service
metadata:
  name: ms-catalogo
  namespace: microservices-ns
  labels:
    app: ms-catalogo
spec:
  selector:
    app: ms-catalogo
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP