# 06-postgres-deployment-service.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: microservices-ns
  labels:
    app: postgres-db
spec:
  replicas: 1 # Una sola instancia para desarrollo
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres-db
        image: postgres:15 # Versión estable de PostgreSQL
        ports:
        - containerPort: 5432 # Puerto estándar de PostgreSQL
        envFrom: # Cargar variables de entorno desde el Secret
        - secretRef:
            name: postgres-credentials
        env: # Variables de entorno adicionales (puedes añadir si es necesario)
          - name: PGDATA # Donde PostgreSQL almacenará sus datos
            value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data # Monta el PVC aquí
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db # Nombre del servicio que tus microservicios usarán para conectar
  namespace: microservices-ns
  labels:
    app: postgres-db
spec:
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: 5432 # Puerto del servicio
      targetPort: 5432 # Puerto del contenedor
  type: ClusterIP # Accesible solo desde dentro del clúster