# 07-rabbitmq-secrets.yml
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: microservices-ns
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: admin
  RABBITMQ_DEFAULT_PASS: admin