server:
  port: 8000

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true    # deja los service-id en minúsculas

      actuator:                         # <-- debía ir al mismo nivel que discovery
        verbose:
          enabled: true                 # imprime predicados y filtros

      routes:
        - id: servicio-publicaciones
          uri: lb://SERVICIO-PUBLICACIONES
          predicates:
            - Path=/publicaciones/**
          filters:
            - StripPrefix=1

        - id: servicio-catalogo
          uri: lb://SERVICIO-CATALOGO
          predicates:
            - Path=/catalogo/**
          filters:
            - StripPrefix=1

        - id: servicio-notificaciones
          uri: lb://SERVICIO-NOTIFICACIONES
          predicates:
            - Path=/notificaciones/**
          filters:
            - StripPrefix=1

        - id: auth-service
          uri: lb://AUTH-SERVICE # Apunta al nombre de servicio de Eureka
          predicates:
            - Path=/authservice/** # Las peticiones a /api/auth/... irán a auth-service
          filters:
            - StripPrefix=1 # Elimina /api/auth del path antes de enviar a auth-service

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "health,info,gateway" # Asegura que 'health' y 'gateway' estén expuestos
  endpoint:
    health:
      show-details: always # Muestra detalles de salud para depuración (opcional, pero útil)
    # ELIMINA o COMENTA la siguiente sección, es la que causa el ERROR:
    # gateway:
    #   enabled: true # Esta línea es la problemática según tus logs. La exposición se maneja con 'exposure.include'